### ISSUE TITLE
Cannot always retrieve data

### ISSUE THREAD

**Issue by RobMahn** [jbaurle/PMStockQuote#10]
Most of the time, I get the error:
ERROR: Couldn't retrieve and process data from Google Finance service. Internal message: Unable to parse JSON (Unexpected character encountered while parsing value: <. Path '', line 0, 

Sometimes the data will be retrieved as though it is not waiting long enough for a response.

The search function never works and gives the same error in a pop-up.

I am using Excel 2013 32-bit on Windows 10 with current updates.

**Comment by jbaurle** [comment]
It seems that Google Finance also stopped it‘s JSON data service, like Yahoo did a couple a month ago.

**Comment by RobMahn** [comment]
Sometimes it does retrieve data, so it would not seem the service is stopped.  Perhaps it is slow or having some other problem today.

**Comment by BradWilks** [comment]
Having the same problem but it is consistent.  This is the same as the problem had with Yahoo.

**Comment by RobMahn** [comment]
Hi,
I’ve found a couple of working solutions that you will find interesting.

One is the attached file with a VB Module.

The other is a different add-in:
http://gaiersoftware.com/Excel/

Rob

**Comment by BradWilks** [comment]
Gaiersoftware works great!  Thanks
