### ISSUE TITLE
was looking for pmstockquote64.xll but now

### ISSUE THREAD

**Issue by quarinteen** [jbaurle/PMStockQuote#11]
I see the other issue opened and found the file. Now my question is does this still work for 2013? I found this via a youtube video for excel 2013. The pmstockquote.xll on the download page says 2018. Is there a 2013 version>

**Comment by jbaurle** [comment]
As I noted on the main page: **The Stock Quote add-in is using the Google Finance service to retrieve the stock quotes. The service seems to be terminated by Google in March 2018. The add-in is currently not working.**
