### ISSUE TITLE
Mutual fund request

### ISSUE THREAD

**Issue by twinchell8** [jbaurle/PMStockQuote#3]
Looks like mutual funds queries return different JSON data that isn't being correctly parsed.  For example, MUTF:VTSAX is not able to be searched in the add on.  If you manually generate the JSON data, it is missing the "symbol" and "exchange" that the deserializer is attempting to parse.  Maybe this is easily corrected since that data does exist, just under different names, "t" and "e" in this case?

Would be really nice to pull mutual fund tickers as well since the Google API supports this. :)

**Comment by jbaurle** [comment]
The JSON returned by Google is wrong and the parser is not tolerant. It's just invalid JSON. I will try to find a solution.

![json](https://user-images.githubusercontent.com/3924999/34565709-2bee5ea0-f15c-11e7-8a65-19c37e8ef676.png)

**Comment by jbaurle** [comment]
With the newest release you are able to query mutual fonds. There is a new item notation (JSON path) logic to access all data available. Starting from the root object you may access for instance the first figure data with **financials/0/f_figures/0/annual**. This notation returns the value as string. To return the value as number, prefix the path with !. The notation is case-sensitive.

=PSQ("NASDAQ:GOOGL";"!financials/0/f_figures/0/annual")
=PSQ("NASDAQ:GOOGL";"avvo")
=PSQ("ETR:DAI";"management/1/name")
=PSQ("MUTF:VTSAX";"!expense_ratio")

Current release
https://github.com/jbaurle/PMStockQuote/releases/tag/Stock_Quote_Add-In_For_Excel_2018_R2

![2018-01-09 13_05_49-clipboard](https://user-images.githubusercontent.com/3924999/34720132-ef60fffc-f53d-11e7-8c58-c85c3671ecdb.png)
