### ISSUE TITLE
Need to specify US exchange (NYSE or NASDAQ) with ticker

### ISSUE THREAD

**Issue by valueshopper** [jbaurle/PMStockQuote#4]
Of the 3215 ticker prices I pull for my spreadsheet, 2858 of them are US listed.  Most of those successfully pulled a price without the exchange being included in the ticker code (i.e. =PSQ(A1) where A1=A) but 168 of them gave me "#N/A".  After I specified the exchange (i.e. =PSQ(A1) where A1=NYSE:A) for those 168 securities (some NYSE, some NASDAQ) they successfully pulled a price.  Many of these were large cap widely traded stocks.  I could not see what made them unique to demand an exchange specification but it implies that to avoid headaches one should simply specify the exchange for all tickers whether US or not.

**Comment by jbaurle** [comment]
The Google Finance API used as replacement of the Yahoo service (in the current version of the Stock Quote Add-In) is somewhat of strange. The search is not very reliable. Always use the exchange notation.
