### ISSUE TITLE
Currency is not working

### ISSUE THREAD

**Issue by ghost** [jbaurle/PMStockQuote#6]
I'm trying to fetch the EURO->USD exchange rate using EURUSD or CURRENCY:EURUSD but it doesn't work (result is N/A)

**Comment by jbaurle** [comment]
Currency rates (e.g. EURUSD or BTCUSD) are not available. The Google Finance API is not returning any values. To verify this, you may open the Search Ticker dialog, query for the currency rate symbol and click the Ticker Data button. The JSON data are not showing any rates.
