### ISSUE TITLE
PMStockQuote folder does not include the PMStockQuote64.xll file

### ISSUE THREAD

**Issue by JK59** [jbaurle/PMStockQuote#7]
The install.bat refer to the PMStockQuote64.xll which is not available.

**Comment by jbaurle** [comment]
You need to download the PMStockQuote.zip file from the releases page.

https://github.com/jbaurle/PMStockQuote/releases

![stockquotereleaser2](https://user-images.githubusercontent.com/3924999/36469076-45f11d42-16e6-11e8-9d2b-1d689d101c91.jpg)
