### ISSUE TITLE
Unable to access Google Finance

### ISSUE THREAD

**Issue by Shakerhill** [jbaurle/PMStockQuote#9]
Now getting the following error

ERROR: Couldn't retrieve and process data   from Google Finance service. Internal message: Unable to parse JSON   (Unexpected character encountered while parsing value: <. Path '', line 0,   position 0.).
--

**Comment by jbaurle** [comment]
It seems that Google Finance also stopped it‘s JSON data service, like Yahoo did a couple a month ago.

**Comment by Shakerhill** [comment]
Damn

**Comment by Rio2017** [comment]
Thank you for the heads-up!


Sincerely,

Dr. Richard Vedder
Professor of Information Technology
Information Technology & Decision Sciences Department (ITDS) Business Leadership Bldg., Room 312-J University of North Texas
1307 West Highland St. #305249
Denton, TX 76201-5017
USA
Voice: 940-565-3104
FAX: 940-565-4935
Email: vedder@unt.edu
http://www.cob.unt.edu/itds/

________________________________
